bodies: [BODY base link, BODY main insertion link, BODY pitch back link, BODY pitch
    bottom link, BODY pitch end link, BODY pitch front link, BODY pitch top link,
  BODY tool gripper1 link, BODY tool gripper2 link, BODY tool pitch link, BODY tool
    roll link, BODY tool yaw link, BODY yaw link]
joints: [JOINT pitch end link-main insertion link, JOINT yaw link-pitch back link,
  JOINT pitch back link-pitch bottom link, JOINT pitch bottom link-pitch end link,
  JOINT yaw link-pitch front link, JOINT pitch back link-pitch top link, JOINT tool
    yaw link-tool gripper1 link, JOINT tool yaw link-tool gripper2 link, JOINT tool
    roll link-tool pitch link, JOINT main insertion link-tool roll link, JOINT tool
    pitch link-tool yaw link, JOINT base link-yaw link]
high resolution path: ../../../models/blender_afmb/psm/high_res/
low resolution path: ../../../models/blender_afmb/psm/low_res/
ignore inter-collision: 'True'
BODY base link:
  name: base link
  mesh: base link.STL
  mass: 2.016
  scale: 1.0
  location:
    orientation: {p: -0.0, r: 0.0, y: -1.571}
    position: {x: 0.0, y: 0.0, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.086, z: -0.043}
  color rgba: {a: 1.0, b: 0.6151, g: 0.4803, r: 0.3012}
BODY main insertion link:
  name: main insertion link
  mesh: main insertion link.STL
  mass: 0.225
  scale: 1.0
  location:
    orientation: {p: 1.57, r: 1.32, y: -0.252}
    position: {x: 0.486, y: -0.0, z: 0.432}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.169, y: -0.006, z: 0.0}
  color rgba: {a: 0.4, b: 0.0588, g: 0.5569, r: 1.0}
BODY pitch back link:
  name: pitch back link
  mesh: pitch back link.STL
  mass: 0.985
  scale: 1.0
  location:
    orientation: {p: -1.862, r: -1.57, y: -0.002}
    position: {x: -0.03, y: 0.0, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.041, y: -0.025, z: 0.0}
  color rgba: {a: 1.0, b: 0.9294, g: 0.3032, r: 0.1689}
BODY pitch bottom link:
  name: pitch bottom link
  mesh: pitch bottom link.STL
  mass: 0.446
  scale: 1.0
  location:
    orientation: {p: -0.001, r: -1.571, y: -0.001}
    position: {x: -0.073, y: 0.0, z: 0.144}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.257, y: -0.021, z: 0.0}
  color rgba: {a: 1.0, b: 0.0668, g: 0.0156, r: 0.008}
BODY pitch end link:
  name: pitch end link
  mesh: pitch end link.STL
  mass: 2.091
  scale: 1.0
  location:
    orientation: {p: -0.001, r: -1.571, y: -0.001}
    position: {x: 0.443, y: -0.001, z: 0.144}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.015, y: -0.107, z: 0.0}
  color rgba: {a: 1.0, b: 0.4479, g: 0.1627, r: 0.1418}
BODY pitch front link:
  name: pitch front link
  mesh: pitch front link.STL
  mass: 0.074
  scale: 1.0
  location:
    orientation: {p: -1.862, r: -1.57, y: -0.002}
    position: {x: 0.066, y: -0.0, z: -0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.075, y: 0.0, z: 0.041}
  color rgba: {a: 1.0, b: 0.9294, g: 0.1705, r: 0.1637}
BODY pitch top link:
  name: pitch top link
  mesh: pitch top link.STL
  mass: 0.178
  scale: 1.0
  location:
    orientation: {p: -0.001, r: -1.571, y: -0.001}
    position: {x: -0.069, y: 0.0, z: 0.18}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.257, y: -0.001, z: 0.0}
  color rgba: {a: 1.0, b: 0.0, g: 0.4643, r: 0.9294}
BODY tool gripper1 link:
  name: tool gripper1 link
  mesh: tool gripper1 link.STL
  mass: 0.001
  scale: 1.0
  location:
    orientation: {p: 3.141, r: 1.571, y: -0.0}
    position: {x: 0.486, y: -0.001, z: 0.007}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.0, y: 0.004, z: -0.001}
  color rgba: {a: 1.0, b: 0.9373, g: 0.8235, r: 0.7961}
BODY tool gripper2 link:
  name: tool gripper2 link
  mesh: tool gripper2 link.STL
  mass: 0.001
  scale: 1.0
  location:
    orientation: {p: 3.141, r: 1.571, y: -0.0}
    position: {x: 0.486, y: -0.001, z: 0.007}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.004, z: 0.001}
  color rgba: {a: 1.0, b: 0.9373, g: 0.8235, r: 0.7961}
BODY tool pitch link:
  name: tool pitch link
  mesh: tool pitch link.STL
  mass: 0.001
  scale: 1.0
  location:
    orientation: {p: 1.57, r: 3.14, y: -0.002}
    position: {x: 0.486, y: -0.001, z: 0.016}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.004, y: -0.0, z: 0.0}
  color rgba: {a: 1.0, b: 0.9373, g: 0.8235, r: 0.7961}
BODY tool roll link:
  name: tool roll link
  mesh: tool roll link.STL
  mass: 0.001
  scale: 1.0
  location:
    orientation: {p: -0.0, r: -3.141, y: -1.571}
    position: {x: 0.486, y: -0.001, z: 0.016}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.0, y: -0.0, z: -0.004}
  color rgba: {a: 1.0, b: 0.9373, g: 0.8235, r: 0.7961}
BODY tool yaw link:
  name: tool yaw link
  mesh: tool yaw link.STL
  mass: 0.001
  scale: 1.0
  location:
    orientation: {p: 3.141, r: 1.571, y: -0.0}
    position: {x: 0.486, y: -0.001, z: 0.007}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.0, z: -0.0}
  color rgba: {a: 1.0, b: 0.9373, g: 0.8235, r: 0.7961}
BODY yaw link:
  name: yaw link
  mesh: yaw link.STL
  mass: 1.47
  scale: 1.0
  location:
    orientation: {p: -1.571, r: -1.571, y: 1.569}
    position: {x: 0.0, y: 0.0, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.061, y: 0.0, z: 0.043}
  color rgba: {a: 1.0, b: 0.9294, g: 0.2719, r: 0.2854}
JOINT pitch end link-main insertion link:
  name: pitch end link-main insertion link
  parent: BODY pitch end link
  child: BODY main insertion link
  parent axis: {x: -0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.043, y: -0.288, z: -0.0}
  child axis: {x: 1.0, y: 0.0, z: 0.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.24, low: 0.0}
  enable motor: 0
  max motor impulse: 0
  type: prismatic
  offset: 3.141
JOINT yaw link-pitch back link:
  name: yaw link-pitch back link
  parent: BODY yaw link
  child: BODY pitch back link
  parent axis: {x: -0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: -0.0, z: 0.03}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.942, low: -0.936}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: -0.291
JOINT pitch back link-pitch bottom link:
  name: pitch back link-pitch bottom link
  parent: BODY pitch back link
  child: BODY pitch bottom link
  parent axis: {x: -0.0, y: -0.0, z: 1.0}
  parent pivot: {x: 0.15, y: -0.0, z: -0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.936, low: -0.942}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: 1.861
JOINT pitch bottom link-pitch end link:
  name: pitch bottom link-pitch end link
  parent: BODY pitch bottom link
  child: BODY pitch end link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.516, y: 0.0, z: -0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.942, low: -0.936}
  enable motor: 0
  max motor impulse: 0
  type: revolute
JOINT yaw link-pitch front link:
  name: yaw link-pitch front link
  parent: BODY yaw link
  child: BODY pitch front link
  parent axis: {x: -0.0, y: 1.0, z: 0.0}
  parent pivot: {x: -0.0, y: -0.0, z: -0.066}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.942, low: -0.936}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: -0.291
JOINT pitch back link-pitch top link:
  name: pitch back link-pitch top link
  parent: BODY pitch back link
  child: BODY pitch top link
  parent axis: {x: -0.0, y: -0.0, z: 1.0}
  parent pivot: {x: 0.184, y: 0.014, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.936, low: -0.942}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: 1.861
JOINT tool yaw link-tool gripper1 link:
  name: tool yaw link-tool gripper1 link
  parent: BODY tool yaw link
  child: BODY tool gripper1 link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.0, y: -0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 1.0, low: 0.0}
  enable motor: 0
  max motor impulse: 0
  type: revolute
JOINT tool yaw link-tool gripper2 link:
  name: tool yaw link-tool gripper2 link
  parent: BODY tool yaw link
  child: BODY tool gripper2 link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.0, y: -0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 1.0, low: 0.0}
  enable motor: 0
  max motor impulse: 0
  type: revolute
JOINT tool roll link-tool pitch link:
  name: tool roll link-tool pitch link
  parent: BODY tool roll link
  child: BODY tool pitch link
  parent axis: {x: 0.0, y: 1.0, z: -0.0}
  parent pivot: {x: 0.0, y: -0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 1.571, low: -1.571}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: -1.571
JOINT main insertion link-tool roll link:
  name: main insertion link-tool roll link
  parent: BODY main insertion link
  child: BODY tool roll link
  parent axis: {x: 1.0, y: 0.0, z: -0.0}
  parent pivot: {x: 0.416, y: 0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 3.142, low: -3.142}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: 3.141
JOINT tool pitch link-tool yaw link:
  name: tool pitch link-tool yaw link
  parent: BODY tool pitch link
  child: BODY tool yaw link
  parent axis: {x: 0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.009, y: -0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 1.571, low: -1.571}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: -1.571
JOINT base link-yaw link:
  name: base link-yaw link
  parent: BODY base link
  child: BODY yaw link
  parent axis: {x: -0.001, y: -1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 1.599, low: -1.605}
  enable motor: 0
  max motor impulse: 0
  type: revolute
  offset: 1.57
