bodies: [BODY base, BODY link1, BODY link2, BODY link3, BODY link4, BODY link5, BODY
    link6, BODY link7]
joints: [JOINT base-link1, JOINT link1-link2, JOINT link2-link3, JOINT link3-link4,
  JOINT link4-link5, JOINT link5-link6, JOINT link6-link7]
high resolution path: ../../../models/kuka_lwr/high_res/
low resolution path: ../../../models/kuka_lwr/low_res/
BODY base:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.001, y: -0.0, z: 0.06}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: 0.0, y: 0.0, z: 0.0}
  mass: 0.0
  mesh: base.STL
  name: base
  scale: 1.0
BODY link1:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.017, z: 0.134}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: 0.0, y: -0.0, z: 0.103}
  mass: 1.0
  mesh: link1.STL
  name: link1
  scale: 1.0
BODY link2:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.074, z: 0.009}
  location:
    orientation: {p: -0.0, r: -1.571, y: 0.0}
    position: {x: 0.0, y: 0.013, z: 0.312}
  mass: 1.0
  mesh: link2.STL
  name: link2
  scale: 1.0
BODY link3:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.017, z: 0.134}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: -0.0, y: 0.004, z: 0.505}
  mass: 1.0
  mesh: link3.STL
  name: link3
  scale: 1.0
BODY link4:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.001, y: 0.081, z: 0.008}
  location:
    orientation: {p: -0.0, r: 1.571, y: 0.0}
    position: {x: 0.0, y: -0.009, z: 0.708}
  mass: 1.0
  mesh: link4.STL
  name: link4
  scale: 1.0
BODY link5:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.017, z: 0.129}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: -0.002, y: -0.001, z: 0.909}
  mass: 1.0
  mesh: link5.STL
  name: link5
  scale: 1.0
BODY link6:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.0, y: 0.007, z: 0.068}
  location:
    orientation: {p: -0.0, r: -1.571, y: 0.0}
    position: {x: 0.0, y: -0.053, z: 1.113}
  mass: 1.0
  mesh: link6.STL
  name: link6
  scale: 1.0
BODY link7:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.006, y: 0.0, z: 0.015}
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: -0.003, y: 0.0, z: 1.163}
  mass: 1.0
  mesh: link7.STL
  name: link7
  scale: 1.0
JOINT base-link1:
  child: BODY link1
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: base-link1
  parent: BODY base
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.0, y: -0.0, z: 0.103}
JOINT link1-link2:
  child: BODY link2
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link1-link2
  parent: BODY link1
  parent axis: {x: 0.0, y: 1.0, z: -0.0}
  parent pivot: {x: -0.0, y: 0.013, z: 0.209}
JOINT link2-link3:
  child: BODY link3
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link2-link3
  parent: BODY link2
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: -0.0, y: -0.194, z: -0.009}
JOINT link3-link4:
  child: BODY link4
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link3-link4
  parent: BODY link3
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: 0.0, y: -0.013, z: 0.202}
JOINT link4-link5:
  child: BODY link5
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link4-link5
  parent: BODY link4
  parent axis: {x: 0.0, y: 1.0, z: -0.0}
  parent pivot: {x: -0.002, y: 0.202, z: -0.008}
JOINT link5-link6:
  child: BODY link6
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link5-link6
  parent: BODY link5
  parent axis: {x: 0.0, y: 1.0, z: -0.0}
  parent pivot: {x: 0.002, y: -0.052, z: 0.204}
JOINT link6-link7:
  child: BODY link7
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: link6-link7
  parent: BODY link6
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: -0.003, y: -0.05, z: 0.053}
