bodies: [BODY r_gripper_l_finger_link, BODY r_gripper_l_finger_tip_link, BODY r_gripper_palm_link,
  BODY r_gripper_r_finger_link, BODY r_gripper_r_finger_tip_link]
joints: [JOINT r_gripper_palm_link-r_gripper_l_finger_link, JOINT r_gripper_l_finger_link-r_gripper_l_finger_tip_link,
  JOINT r_gripper_palm_link-r_gripper_r_finger_link, JOINT r_gripper_r_finger_link-r_gripper_r_finger_tip_link]
high resolution path: ../../../models/grippers/pr2_gripper/high_res/
low resolution path: ../../../models/grippers/pr2_gripper/low_res/
ignore inter-collision: 'True'
BODY r_gripper_l_finger_link:
  name: r_gripper_l_finger_link
  mesh: r_gripper_l_finger_link.STL
  mass: 0.171
  scale: 1.0
  location:
    orientation: {p: -0.0, r: 0.0, y: -3.141}
    position: {x: -0.077, y: -0.01, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.043, y: 0.018, z: 0.0}
  color rgba: {a: 1.0, b: 0.1679, g: 0.1679, r: 0.1679}
BODY r_gripper_l_finger_tip_link:
  name: r_gripper_l_finger_tip_link
  mesh: r_gripper_l_finger_tip_link.STL
  mass: 0.044
  scale: 1.0
  location:
    orientation: {p: 0.0, r: -3.142, y: 0.0}
    position: {x: -0.168, y: -0.015, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.003, y: 0.006, z: -0.0}
  color rgba: {a: 1.0, b: 0.0908, g: 0.0908, r: 0.0908}
BODY r_gripper_palm_link:
  name: r_gripper_palm_link
  mesh: r_gripper_palm_link.STL
  mass: 0.58
  scale: 1.0
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: 0.0, y: 0.0, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.078, y: -0.0, z: 0.0}
  color rgba: {a: 1.0, b: 0.4818, g: 0.8, r: 0.0}
BODY r_gripper_r_finger_link:
  name: r_gripper_r_finger_link
  mesh: r_gripper_r_finger_link.STL
  mass: 0.174
  scale: 1.0
  location:
    orientation: {p: 3.142, r: -0.0, y: -0.0}
    position: {x: -0.077, y: 0.01, z: 0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.043, y: 0.018, z: 0.0}
  color rgba: {a: 1.0, b: 0.1574, g: 0.1574, r: 0.1574}
BODY r_gripper_r_finger_tip_link:
  name: r_gripper_r_finger_tip_link
  mesh: r_gripper_r_finger_tip_link.STL
  mass: 0.044
  scale: 1.0
  location:
    orientation: {p: -0.0, r: 0.0, y: 0.0}
    position: {x: -0.168, y: 0.015, z: -0.0}
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.003, y: 0.006, z: -0.0}
  color rgba: {a: 1.0, b: 0.0607, g: 0.0607, r: 0.0607}
JOINT r_gripper_palm_link-r_gripper_l_finger_link:
  name: r_gripper_palm_link-r_gripper_l_finger_link
  parent: BODY r_gripper_palm_link
  child: BODY r_gripper_l_finger_link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.077, y: -0.01, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.548, low: 0.0}
  max motor impulse: 0.01
  type: revolute
  offset: 3.142
JOINT r_gripper_l_finger_link-r_gripper_l_finger_tip_link:
  name: r_gripper_l_finger_link-r_gripper_l_finger_tip_link
  parent: BODY r_gripper_l_finger_link
  child: BODY r_gripper_l_finger_tip_link
  parent axis: {x: 0.0, y: -0.0, z: -1.0}
  parent pivot: {x: 0.091, y: 0.005, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.548, low: 0.0}
  max motor impulse: 0.01
  type: revolute
JOINT r_gripper_palm_link-r_gripper_r_finger_link:
  name: r_gripper_palm_link-r_gripper_r_finger_link
  parent: BODY r_gripper_palm_link
  child: BODY r_gripper_r_finger_link
  parent axis: {x: 0.0, y: 0.0, z: -1.0}
  parent pivot: {x: -0.077, y: 0.01, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.548, low: 0.0}
  max motor impulse: 0.01
  type: revolute
JOINT r_gripper_r_finger_link-r_gripper_r_finger_tip_link:
  name: r_gripper_r_finger_link-r_gripper_r_finger_tip_link
  parent: BODY r_gripper_r_finger_link
  child: BODY r_gripper_r_finger_tip_link
  parent axis: {x: 0.0, y: 0.0, z: -1.0}
  parent pivot: {x: 0.091, y: 0.005, z: 0.0}
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  joint limits: {high: 0.548, low: 0.0}
  max motor impulse: 0.01
  type: revolute
