bodies: [hook]
joints: []
high resolution path: ../resources/models/tools/high_res/
low resolution path: ../resources/models/tools/low_res/

hook:
 name: hook1
 mass: 0.08
 mesh: Hook.STL
 scale: 1.0
 friction: {static: 0.8}
 color: red
