bodies: [BODY ArmParallel, BODY ArmParallel1, BODY BottomArm, BODY Link, BODY OutPitch
    Shoulder, BODY Top Panel, BODY WristPitch, BODY WristPlatform, BODY WristRoll,
  BODY WristYaw]
joints: [JOINT OutPitch Shoulder-ArmParallel, JOINT OutPitch Shoulder-ArmParallel1,
  JOINT ArmParallel-BottomArm, JOINT ArmParallel1-Link, JOINT Top Panel-OutPitch Shoulder,
  JOINT WristPlatform-WristPitch, JOINT BottomArm-WristPlatform, JOINT WristYaw-WristRoll,
  JOINT WristPitch-WristYaw]
high resolution path: /home/adnan/chai3d/modules/BULLET/bin/resources/models/MTM/high_res/
low resolution path: /home/adnan/chai3d/modules/BULLET/bin/resources/models/MTM/low_res/
BODY ArmParallel:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.012, y: -0.109, z: -0.02}
  location:
    orientation: {p: 0.0, r: 1.571, y: -3.142}
    position: {x: -0.321, y: 0.718, z: 0.355}
  mass: 1.0
  mesh: ArmParallel.STL
  name: ArmParallel
  scale: 1.0
BODY ArmParallel1:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.038, y: 0.0, z: 0.006}
  location:
    orientation: {p: 0.0, r: 1.571, y: -3.142}
    position: {x: -0.32, y: 0.656, z: 0.356}
  mass: 1.0
  mesh: ArmParallel1.STL
  name: ArmParallel1
  scale: 1.0
BODY BottomArm:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.188, y: 0.008, z: -0.0}
  location:
    orientation: {p: 0.0, r: 1.571, y: -3.142}
    position: {x: -0.319, y: 0.718, z: 0.076}
  mass: 1.0
  mesh: BottomArm.STL
  name: BottomArm
  scale: 1.0
BODY Link:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.14, z: -0.007}
  location:
    orientation: {p: 0.0, r: 1.571, y: -3.142}
    position: {x: -0.22, y: 0.701, z: 0.357}
  mass: 1.0
  mesh: Link.STL
  name: Link
  scale: 1.0
BODY OutPitch Shoulder:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.003, y: 0.035, z: -0.119}
  location:
    orientation: {p: -0.0, r: 0.0, y: -3.142}
    position: {x: -0.343, y: 0.718, z: 0.546}
  mass: 1.0
  mesh: OutPitch Shoulder.STL
  name: OutPitch Shoulder
  scale: 1.0
BODY Top Panel:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: -0.008, y: 0.064, z: 0.029}
  location:
    orientation: {p: -0.0, r: 0.0, y: -3.142}
    position: {x: -0.343, y: 0.718, z: 0.572}
  mass: 0.0
  mesh: Top Panel.STL
  name: Top Panel
  scale: 1.0
BODY WristPitch:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.041, z: -0.037}
  location:
    orientation: {p: -0.0, r: -1.571, y: -3.142}
    position: {x: 0.047, y: 0.718, z: 0.225}
  mass: 1.0
  mesh: WristPitch.STL
  name: WristPitch
  scale: 1.0
BODY WristPlatform:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: -0.055, z: -0.055}
  location:
    orientation: {p: -0.0, r: 0.0, y: -3.142}
    position: {x: 0.047, y: 0.718, z: 0.225}
  mass: 1.0
  mesh: WristPlatform.STL
  name: WristPlatform
  scale: 1.0
BODY WristRoll:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.0, y: 0.0, z: 0.036}
  location:
    orientation: {p: -1.571, r: -3.142, y: 0.0}
    position: {x: 0.01, y: 0.718, z: 0.225}
  mass: 1.0
  mesh: WristRoll.STL
  name: WristRoll
  scale: 1.0
BODY WristYaw:
  color: random
  inertial offset:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0.031, y: 0.0, z: -0.031}
  location:
    orientation: {p: -0.0, r: 0.0, y: -3.142}
    position: {x: 0.047, y: 0.718, z: 0.225}
  mass: 1.0
  mesh: WristYaw.STL
  name: WristYaw
  scale: 1.0
JOINT OutPitch Shoulder-ArmParallel:
  child: BODY ArmParallel
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 1.047, low: -1.047}
  max motor impulse: 0
  name: OutPitch Shoulder-ArmParallel
  parent: BODY OutPitch Shoulder
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: -0.023, y: -0.0, z: -0.191}
JOINT OutPitch Shoulder-ArmParallel1:
  child: BODY ArmParallel1
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.349, low: -0.349}
  max motor impulse: 0
  name: OutPitch Shoulder-ArmParallel1
  parent: BODY OutPitch Shoulder
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: -0.023, y: 0.062, z: -0.191}
JOINT ArmParallel-BottomArm:
  child: BODY BottomArm
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: ArmParallel-BottomArm
  parent: BODY ArmParallel
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.002, y: -0.279, z: 0.0}
JOINT ArmParallel1-Link:
  child: BODY Link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: ArmParallel1-Link
  parent: BODY ArmParallel1
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.1, y: 0.001, z: 0.045}
JOINT Top Panel-OutPitch Shoulder:
  child: BODY OutPitch Shoulder
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 1.047, low: -1.047}
  max motor impulse: 0
  name: Top Panel-OutPitch Shoulder
  parent: BODY Top Panel
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: -0.0, y: -0.0, z: -0.026}
JOINT WristPlatform-WristPitch:
  child: BODY WristPitch
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 1.571, low: -1.571}
  max motor impulse: 0
  name: WristPlatform-WristPitch
  parent: BODY WristPlatform
  parent axis: {x: 0.0, y: 1.0, z: -0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT BottomArm-WristPlatform:
  child: BODY WristPlatform
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: BottomArm-WristPlatform
  parent: BODY BottomArm
  parent axis: {x: -0.0, y: 1.0, z: -0.0}
  parent pivot: {x: -0.366, y: 0.149, z: -0.0}
JOINT WristYaw-WristRoll:
  child: BODY WristRoll
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 1.571, low: -1.571}
  max motor impulse: 0
  name: WristYaw-WristRoll
  parent: BODY WristYaw
  parent axis: {x: -1.0, y: 0.0, z: -0.0}
  parent pivot: {x: 0.037, y: 0.0, z: 0.0}
JOINT WristPitch-WristYaw:
  child: BODY WristYaw
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: WristPitch-WristYaw
  parent: BODY WristPitch
  parent axis: {x: 0.0, y: -1.0, z: -0.0}
  parent pivot: {x: -0.0, y: 0.0, z: 0.0}
