bodies: [BODY calib_kuka_arm_base_link, BODY kuka_arm_1_link, BODY kuka_arm_2_link,
  BODY kuka_arm_3_link, BODY kuka_arm_4_link, BODY kuka_arm_5_link, BODY kuka_arm_6_link,
  BODY kuka_arm_7_link]
joints: [JOINT kuka_arm_0_joint, JOINT kuka_arm_1_joint, JOINT kuka_arm_2_joint, JOINT
    kuka_arm_3_joint, JOINT kuka_arm_4_joint, JOINT kuka_arm_5_joint, JOINT kuka_arm_6_joint]
high resolution path: /home/adnan/bullet3/data/kuka_lwr/meshes_arm/
low resolution path: /home/adnan/bullet3/data/kuka_lwr/meshes_arm/convex/
BODY calib_kuka_arm_base_link:
  collision mesh: arm_base_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.0
  mesh: arm_base.stl
  name: calib_kuka_arm_base_link
  scale: 1.0
BODY kuka_arm_1_link:
  collision mesh: arm_segment_a_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 2.02
  mesh: arm_segment_a.stl
  name: kuka_arm_1_link
  scale: 1.0
BODY kuka_arm_2_link:
  collision mesh: arm_segment_b_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 1.98
  mesh: arm_segment_b.stl
  name: kuka_arm_2_link
  scale: 1.0
BODY kuka_arm_3_link:
  collision mesh: arm_segment_a_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 2.02
  mesh: arm_segment_a.stl
  name: kuka_arm_3_link
  scale: 1.0
BODY kuka_arm_4_link:
  collision mesh: arm_segment_b_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 1.98
  mesh: arm_segment_b.stl
  name: kuka_arm_4_link
  scale: 1.0
BODY kuka_arm_5_link:
  collision mesh: arm_segment_last_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 2.0
  mesh: arm_segment_last.stl
  name: kuka_arm_5_link
  scale: 1.0
BODY kuka_arm_6_link:
  collision mesh: arm_wrist_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 2.0
  mesh: arm_wrist.stl
  name: kuka_arm_6_link
  scale: 1.0
BODY kuka_arm_7_link:
  collision mesh: arm_flanche_convex.stl
  color: random
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 2.0
  mesh: arm_flanche.stl
  name: kuka_arm_7_link
  scale: 1.0
JOINT kuka_arm_0_joint:
  child: BODY kuka_arm_1_link
  child axis: {x: -0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 2.967, low: -2.967}
  max motor impulse: 0
  name: kuka_arm_0_joint
  parent: BODY calib_kuka_arm_base_link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.11}
JOINT kuka_arm_1_joint:
  child: BODY kuka_arm_2_link
  child axis: {x: 0.0, y: -1.0, z: 0.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.2}
  enable motor: 0
  joint limits: {high: 1.571, low: -1.571}
  max motor impulse: 0
  name: kuka_arm_1_joint
  parent: BODY kuka_arm_1_link
  parent axis: {x: 0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.2}
JOINT kuka_arm_2_joint:
  child: BODY kuka_arm_3_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: -0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 2.967, low: -2.967}
  max motor impulse: 0
  name: kuka_arm_2_joint
  parent: BODY kuka_arm_2_link
  parent axis: {x: -0.0, y: -0.0, z: -1.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT kuka_arm_3_joint:
  child: BODY kuka_arm_4_link
  child axis: {x: 0.0, y: -1.0, z: 0.0}
  child pivot: {x: -0.0, y: -0.0, z: 0.2}
  enable motor: 0
  joint limits: {high: 2.094, low: -2.094}
  max motor impulse: 0
  name: kuka_arm_3_joint
  parent: BODY kuka_arm_3_link
  parent axis: {x: 0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.2}
JOINT kuka_arm_4_joint:
  child: BODY kuka_arm_5_link
  child axis: {x: -0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 2.967, low: -2.967}
  max motor impulse: 0
  name: kuka_arm_4_joint
  parent: BODY kuka_arm_4_link
  parent axis: {x: 0.0, y: 0.0, z: -1.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT kuka_arm_5_joint:
  child: BODY kuka_arm_6_link
  child axis: {x: 0.0, y: 1.0, z: 0.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 2.094, low: -2.094}
  max motor impulse: 0
  name: kuka_arm_5_joint
  parent: BODY kuka_arm_5_link
  parent axis: {x: 0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.19}
JOINT kuka_arm_6_joint:
  child: BODY kuka_arm_7_link
  child axis: {x: -0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 2.967, low: -2.967}
  max motor impulse: 0
  name: kuka_arm_6_joint
  parent: BODY kuka_arm_6_link
  parent axis: {x: -0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.078}
