bodies: [BODY mtmr_top_panel, BODY mtmr_outer_yaw_link, BODY mtmr_back_parallel_link,
  BODY mtmr_top_parallel_link, BODY mtmr_bottom_parallel_link, BODY mtmr_wrist_platform_link,
  BODY mtmr_wrist_pitch_link, BODY mtmr_wrist_yaw_link, BODY mtmr_wrist_roll_link]
joints: [JOINT outer_yaw, JOINT shoulder_pitch, JOINT shoulder_pitch_parallel, JOINT
    elbow_pitch, JOINT wrist_platform, JOINT wrist_pitch, JOINT wrist_yaw, JOINT wrist_roll]
high resolution path: /home/adnan/dvrk_ws/src/dvrk-ros/dvrk_model/meshes/mtm/
low resolution path: /home/adnan/dvrk_ws/src/dvrk-ros/dvrk_model/meshes/mtm/
BODY mtmr_top_panel:
  collision mesh: Top Panel.STL
  color: random
  inertial: {ix: 9.0, iy: 9.0, iz: 9.0}
  inertial offset:
    orientation: {p: 0.0, r: 0.0, y: 0.0}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.0
  mesh: Top Panel.STL
  name: mtmr_top_panel
  scale: 1.0
BODY mtmr_outer_yaw_link:
  collision mesh: OutPitch_Shoulder.STL
  color: random
  inertial: {ix: 10.0, iy: 10.0, iz: 10.0}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 1.0
  mesh: OutPitch_Shoulder.STL
  name: mtmr_outer_yaw_link
  scale: 1.0
BODY mtmr_back_parallel_link:
  collision mesh: ArmParallel.STL
  color: random
  inertial: {ix: 9.0, iy: 9.0, iz: 9.0}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.9
  mesh: ArmParallel.STL
  name: mtmr_back_parallel_link
  scale: 1.0
BODY mtmr_top_parallel_link:
  collision mesh: ArmParallel1.STL
  color: random
  inertial: {ix: 5.0, iy: 5.0, iz: 5.0}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.5
  mesh: ArmParallel1.STL
  name: mtmr_top_parallel_link
  scale: 1.0
BODY mtmr_bottom_parallel_link:
  collision mesh: BottomArm.STL
  color: random
  inertial: {ix: 0.1, iy: 0.1, iz: 0.1}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.8
  mesh: BottomArm.STL
  name: mtmr_bottom_parallel_link
  scale: 1.0
BODY mtmr_wrist_platform_link:
  collision mesh: WristPlatform.STL
  color: random
  inertial: {ix: 0.1, iy: 0.1, iz: 0.1}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.4
  mesh: WristPlatform.STL
  name: mtmr_wrist_platform_link
  scale: 1.0
BODY mtmr_wrist_pitch_link:
  collision mesh: WristPitch.STL
  color: random
  inertial: {ix: 0.1, iy: 0.1, iz: 0.1}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.2
  mesh: WristPitch.STL
  name: mtmr_wrist_pitch_link
  scale: 1.0
BODY mtmr_wrist_yaw_link:
  collision mesh: WristYaw.STL
  color: random
  inertial: {ix: 0.1, iy: 0.1, iz: 0.1}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.2
  mesh: WristYaw.STL
  name: mtmr_wrist_yaw_link
  scale: 1.0
BODY mtmr_wrist_roll_link:
  collision mesh: WristRoll.STL
  color: random
  inertial: {ix: 0.1, iy: 0.1, iz: 0.1}
  location:
    orientation: {p: 0, r: 0, y: 0}
    position: {x: 0, y: 0, z: 0}
  mass: 0.1
  mesh: WristRoll.STL
  name: mtmr_wrist_roll_link
  scale: 1.0
JOINT outer_yaw:
  child: BODY mtmr_outer_yaw_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.19}
  enable motor: 0
  joint limits: {high: 0.785, low: -1.309}
  max motor impulse: 0
  name: outer_yaw
  parent: BODY mtmr_top_panel
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.0, y: 0.0, z: -0.19}
JOINT shoulder_pitch:
  child: BODY mtmr_back_parallel_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: shoulder_pitch
  parent: BODY mtmr_outer_yaw_link
  parent axis: {x: -0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: -0.19}
JOINT shoulder_pitch_parallel:
  child: BODY mtmr_top_parallel_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.065}
  enable motor: 0
  joint limits: {high: 1.571, low: -1.571}
  max motor impulse: 0
  name: shoulder_pitch_parallel
  parent: BODY mtmr_outer_yaw_link
  parent axis: {x: -0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: -0.19}
JOINT elbow_pitch:
  child: BODY mtmr_bottom_parallel_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: elbow_pitch
  parent: BODY mtmr_back_parallel_link
  parent axis: {x: 0.0, y: 0.0, z: 1.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT wrist_platform:
  child: BODY mtmr_wrist_platform_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 4.276, low: -1.047}
  max motor impulse: 0
  name: wrist_platform
  parent: BODY mtmr_bottom_parallel_link
  parent axis: {x: 0.0, y: -1.0, z: 0.0}
  parent pivot: {x: 0.0, y: -0.151, z: 0.0}
JOINT wrist_pitch:
  child: BODY mtmr_wrist_pitch_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 3.142, low: -1.571}
  max motor impulse: 0
  name: wrist_pitch
  parent: BODY mtmr_wrist_platform_link
  parent axis: {x: 0.0, y: 1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT wrist_yaw:
  child: BODY mtmr_wrist_yaw_link
  child axis: {x: 0.0, y: 0.0, z: 1.0}
  child pivot: {x: 0.0, y: -0.0, z: -0.0}
  enable motor: 0
  joint limits: {high: 0.785, low: -0.785}
  max motor impulse: 0
  name: wrist_yaw
  parent: BODY mtmr_wrist_pitch_link
  parent axis: {x: -0.0, y: -1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
JOINT wrist_roll:
  child: BODY mtmr_wrist_roll_link
  child axis: {x: 0.0, y: -0.0, z: -1.0}
  child pivot: {x: 0.0, y: 0.0, z: 0.039}
  enable motor: 0
  joint limits: {high: 4.712, low: -4.712}
  max motor impulse: 0
  name: wrist_roll
  parent: BODY mtmr_wrist_yaw_link
  parent axis: {x: -0.0, y: -1.0, z: 0.0}
  parent pivot: {x: 0.0, y: 0.0, z: 0.0}
