# This is the base file for Coordination Application
path: ../resources/config/
world_config: world_config.yaml
multibody_config: puzzle1.yaml
color_config: colors.yaml
gripper_configs: ["Default", "MTMR", "MTML", "Novint Falcon", "Geomagic Touch", "PHANTOM Omni", "Razer Hydra"]
"Default": "gripper_type1.yaml"
"MTMR": "tool_type2.yaml"
"MTML": "gripper_multi_joint2.yaml"
"Novint Falcon": "gripper_single_joint1.yaml"
"Geomagic Touch": "gripper_single_joint1.yaml"
"PHANTOM Omni": "tool_bar.yaml"
"Razer Hydra": "gripper_multi_joint2.yaml"
