links: [gripper_base, gripper_l1, gripper_r1]
joints: [base_l_joint, base_r_joint]
high_res_path: ../resources/models/gripper/high_res/
low_res_path: ../resources/models/gripper/low_res/

gripper_base:
 name: gripper_base
 mass: 0.02
 mesh: BaseLink.STL
 scale: 1.0
 #position: {x: 0.0, y: 0.0, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: purple

gripper_r1:
 name: gripper_r1
 mass: 0.02
 mesh: SingleLinkR1.STL
 scale: 1.0
 position: {x: 0.0, y: 0.085, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: white

gripper_l1:
 name: gripper_l1
 mass: 0.02
 mesh: SingleLinkL1.STL
 scale: 1.0
 position: {x: 0.0, y: -0.085, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: purple

joint_template: &anchor
 name:
 parent:
 child:
 parent_pivot: {x: 0, y: 0, z: 0.5}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: 0.5, high: 1.0}
 enable_motor: 1
 max_motor_impulse: 0.05

base_r_joint:
 name: base_r_joint
 parent: gripper_base
 child: gripper_r1
 parent_pivot: {x: 0, y: 0.085, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low:  0.25, high: -0.5}
 enable_motor: 1
 max_motor_impulse: 0.05

base_l_joint:
 name: base_l_joint
 parent: gripper_base
 child: gripper_l1
 parent_pivot: {x: 0, y: -0.085, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: -0.25, high: 0.5}
 enable_motor: 1
 max_motor_impulse: 0.05
