links: [gripper_base, gripper_l1, gripper_l2, gripper_r1, gripper_r2]
joints: [base_l_joint, left_1_joint, base_r_joint, right_1_joint]
high_res_path: ../resources/models/gripper/high_res/
low_res_path: ../resources/models/gripper/low_res/
color_config: ../resources/config/colors.yaml

gripper_base:
 name: gripper_base
 mass: 0.02
 mesh: BaseLink.STL
 scale: 1.0
 #position: {x: 0.0, y: 0.0, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: red

gripper_r1:
 name: gripper_r1
 mass: 0.02
 mesh: MultiLinkR1.STL
 scale: 1.0
 position: {x: 0.0, y: 0.085, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: red

gripper_l1:
 name: gripper_l1
 mass: 0.02
 mesh: MultiLinkL1.STL
 scale: 1.0
 position: {x: 0.0, y: -0.085, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: white

gripper_r2:
 name: gripper_r2
 mass: 0.02
 mesh: MultiLinkR2.STL
 scale: 1.0
 position: {x: -0.26, y: 0.069, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: red

gripper_l2:
 name: gripper_l2
 mass: 0.02
 mesh: MultiLinkL2.STL
 scale: 1.0
 position: {x: -0.26, y: -0.069, z: 0.0}
 #rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: red

joint_template: &anchor
 name:
 parent:
 child:
 parent_pivot: {x: 0, y: 0, z: 0.5}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: 0.5, high: 1.0}
 enable_motor: 1
 max_motor_impulse: 0.05

base_r_joint:
 name: base_r_joint
 parent: gripper_base
 child: gripper_r1
 parent_pivot: {x: 0, y: 0.085, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: 0.0, high: -0.7}
 enable_motor: 1
 max_motor_impulse: 0.05

base_l_joint:
 name: base_l_joint
 parent: gripper_base
 child: gripper_l1
 parent_pivot: {x: 0, y: -0.085, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: 0.0, high: 0.7}
 enable_motor: 1
 max_motor_impulse: 0.05

right_1_joint:
 name: right_1_joint
 parent: gripper_r1
 child: gripper_r2
 parent_pivot: {x: -0.26, y: 0.069, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: 0.08, high: -0.5}
 enable_motor: 1
 max_motor_impulse: 0.05

left_1_joint:
 name: left_1_joint
 parent: gripper_l1
 child: gripper_l2
 parent_pivot: {x: -0.26, y: -0.069, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 joint_limits: {low: -0.08, high: 0.5}
 enable_motor: 1
 max_motor_impulse: 0.05
