links: [gripper_l1, gripper_r1]
joints: [base_joint]
high_res_path: ../resources/models/grippers/type3/high_res/
low_res_path: ../resources/models/grippers/type3/low_res/

gripper_r1:
 name: gripper_r1
 mass: 0.04
 mesh: SingleLinkR1.STL
 inertial offset: {position: {x: -0.13, y: 0.049, z: 0.003}}
 scale: 1.0
 friction: {static: 0.8}
 color: blue_navy

gripper_l1:
 name: gripper_l1
 mass: 0.04
 mesh: SingleLinkL1.STL
 inertial offset: {position: {x: -0.13, y: -0.049, z: 0.003}}
 scale: 1.0
 friction: {static: 0.8}
 color: white_mint_cream

base_joint:
 name: base_joint
 parent: gripper_r1
 child: gripper_l1
 parent_pivot: {x: 0, y: 0, z: 0.0}
 parent_axis: {x: 0, y: 0, z: 1.0}
 child_pivot: {x: 0, y: 0, z: 0.0}
 child_axis: {x: 0, y: 0, z: 1.0}
 joint_limits: {low:  0.0, high: 0.7}
 enable_motor: 1
 max_motor_impulse: 0.05
