# Generate By: Adnan Munawar
# Testing, no version number yet
links: [link1, link2, link3, link4, link5, link6, link7, link8, link9]
joints: [joint1, joint2]
high_res_path: ../resources/models/puzzle/high_res/
low_res_path: ../resources/models/puzzle/low_res/

link1:
 name: Torus
 mass: 0.8
 mesh: Torus.STL
 scale: 1.0
 position: {x: -1.5, y: -1.5, z: -0.5}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: orange_tomato

link2:
 name: PegBase
 mass: 10.0
 mesh: PegBase.STL
 scale: 1.0
 position: {x: -1.5, y: -1.5, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: blue_navy
 friction: {static: 0.9, rolling: 0.1}

link3:
 name: PuzzleBase
 mass: 8.0
 mesh: PuzzleBase.STL
 scale: 1.0
 position: {x: -1.0, y: 0.0, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: purple_dark_magenta
 friction: {static: 0.9, rolling: 0.1}

link4:
 name: CirclePuzzle
 mass: 0.8
 mesh: CirclePuzzle.STL
 inertial offset: {position: {x: 0.0, y: 0.0, z: 0.135}, rotation: {r: 0.0, p: 0.0, y: 0.0}}
 scale: 1.0
 position: {x: 0.0, y: -0.5, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: yellow
 friction: {linear: 0.8}

link5:
 name: TrianglePuzzle
 mass: 0.8
 mesh: TrianglePuzzle.STL
 inertial offset: {position: {x: 0.0, y: 0.0, z: 0.135}, rotation: {r: 0.0, p: 0.0, y: 0.0}}
 scale: 1.0
 position: {x: 0.0, y: 0.0, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: pink_pale_violet_red
 friction: {linear: 0.8}

link6:
 name: SquarePuzzle
 mass: 0.8
 mesh: SquarePuzzle.STL
 inertial offset: {position: {x: 0.0, y: 0.0, z: 0.135}}
 scale: 1.0
 position: {x: 0.0, y: 0.5, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: blue_corn_flower
 friction: {linear: 0.8}

link7:
 name: HandleLeft
 mass: 0.3
 mesh: HandleLeft.STL
 scale: 1.0
 position: {x: 1.0, y: -0.85, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: orange
 friction: {linear: 0.5}

link8:
 name: HandleRight
 mass: 0.3
 mesh: HandleRight.STL
 scale: 1.0
 position: {x: 1.0, y: 0.85, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: orange_coral
 friction: {linear: 0.5}

link9:
 name: CenterPuzzle
 mass: 1.0
 linear_gain: {P: 200.0, D: 10.0}
 angular_gain: {P: 1.0, D: 1.0}
 mesh: Center.STL
 scale: 1.0
 position: {x: 1.0, y: 0.0, z: -1.0}
 rotation: {r: 0.0, p: 0.0, y: 0.0}
 color: green_medium_spring
 friction: {linear: 0.5}

joint1:
 name: PuzzleLeftJoint
 parent: link9
 child: link7
 parent_axis: {x: 1.0, y: 0, z: 0.0}
 parent_pivot: {x: 0, y: -0.85, z: 0.0}
 child_axis: {x: 1.0, y: 0, z: 0.0}
 child_pivot: {x: 0, y: 0, z: 0}
 joint_limits: {low: -1.2, high: 1.2}
 #enable_motor: 1
 #max_motor_impulse: 0.05

joint2:
 name: PuzzleRightJoint
 parent: link9
 child: link8
 parent_axis: {x: 1.0, y: 0, z: 0}
 parent_pivot: {x: 0, y: 0.85, z: 0.0}
 child_axis: {x: 1.0, y: 0, z: 0}
 child_pivot: {x: 0, y: 0, z: 0}
 joint_limits: {low: -1.2, high: 1.2}
 #enable_motor: 1
 #max_motor_impulse: 0.05
