bodies: [tool_l1]
joints: []
high_res_path: ../resources/models/tools/high_res/
low_res_path: ../resources/models/tools/low_res/

tool_l1:
 name: tool_l1
 mass: 0.08
 mesh: Hook.STL
 scale: 1.0
 friction: {static: 0.8}
 color: red
